version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  k6:
    image: grafana/k6
    depends_on:
      - back-end
    volumes:
      - ./scripts:/scripts
    environment:
      - BASE_URL=http://back-end:3000
    entrypoint: ["/bin/sh", "/scripts/wait-for-services.sh"]

  # jmeter:
  #   image: justb4/jmeter
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./public-test:/tests
  #   entrypoint: ["jmeter", "-n", "-t", "/tests/jmeter-test.jmx", "-l", "/tests/results.jtl"]
  #   environment:
  #     - JMETER_HOST=app
